### ISSUE TITLE
sd_hash in issued CWT? issuer includes all possible disclosures?

### ISSUE THREAD

**Issue by rohanmahy** [ietf-wg-spice/draft-ietf-spice-sd-cwt#10]
currently the sd_hash claim in an SD-CWT is allowed when sent between an issuer and the holder. This is a claim which could not be verified by a verifier. I propose we remove it. If instead the Issuer is required to send salted claim disclosures for every digest in the payload (already proposed in PR #9 ), then the holder has another way of detecting tapering of the unprotected header. 

we also need confidentiality of the disclosures. the most common ways (ex: transport crypto, authenticated encryption of the entire SD-CWT) also provide additional integrity protection of the unprotected header between an issuer and a holder

**Comment by OR13** [comment]
Over taken by events, and addressed in the draft.
