### ISSUE TITLE
Using "keys" in claim names for non-cryptographic keys is potentially confusing

### ISSUE THREAD

**Issue by rohanmahy** [ietf-wg-spice/draft-ietf-spice-sd-cwt#15]
Hi, Mike Jones pointed out that SD-CWT is using "keys" in claim names (ex: `redacted_keys`) in a way which is potentially confusing. We refer to cryptographic keys (ex: confirmation key—`cnf`) and CBOR map keys throughout the document.

The proposal is to rename `redacted_keys` to something else which makes it clear that it is a "map key" and not a cryptographic key. `redacted_elements` or `redacted_values` imply that only the values (and not the claim names) are included.

I propose:

`redacted_map_claims`

**Comment by OR13** [comment]
This naming needs to be consistent for arrays and maps.

- redacted_map_claims
- redacted_array_claim 

?

**Comment by rohanmahy** [comment]
> This naming needs to be consistent for arrays and maps.
> 
>     * redacted_map_claims
>     * redacted_array_claim

I'm not sure. The first is an array of claims that are each items in a map at the same level, and will have an integer key. The second is the map key of a single-element map which represents one item inside an array, and might be represented by the text strong "...".  

This still might be the best suggestion (or least bad). Let's see.

**Comment by mprorock** [comment]
what about:
redacted_claim_XXX <- XXX replaced appropriated
?

**Comment by rohanmahy** [comment]
Mike Prorock asked:
>what about:
>redacted_claim_XXX <- XXX replaced appropriated

Mike, do you mean this?
redacted_claim_map_key
redacted_claim_array_item

Thanks,
-rohan

**Comment by OR13** [comment]
We have agreed to use the language from the CWT RFC, and we have prefixed to make it clear.
We think this is addressed.
