### ISSUE TITLE
Addressing collisions in CBOR map keys at arbitrary depth

### ISSUE THREAD

**Issue by OR13** [ietf-wg-spice/draft-ietf-spice-sd-cwt#19]
As discussed in:
https://github.com/ietf-wg-spice/draft-ietf-spice-sd-cwt/pull/18#discussion_r1798617534

Related references:

- https://www.rfc-editor.org/rfc/rfc9277.html#appendix-B
- https://datatracker.ietf.org/doc/html/rfc8392#section-3
- https://datatracker.ietf.org/doc/html/rfc8392#section-9.1.1
- https://datatracker.ietf.org/doc/html/rfc8392#section-1.1

**Comment by henkbirkholz** [comment]
To tag or not to tag the keys.

**Comment by OR13** [comment]
For now, I have just made the requested assignments very large: https://github.com/ietf-wg-spice/draft-ietf-spice-sd-cwt/pull/20

In the future, we want to use tags, we'll be sharing a proposal for this on the list in a bit.

**Comment by OR13** [comment]
For now we have decided to use tagged 0, and tagged bstr for nested redactions in maps and arrays.

We may consider simple types for map keys if they become well supported in rust, and other languages.
