### ISSUE TITLE
Example of computing a disclosure

### ISSUE THREAD

**Issue by OR13** [ietf-wg-spice/draft-ietf-spice-sd-cwt#22]
Per comment on this list: https://mailarchive.ietf.org/arch/msg/spice/2zCXJoEK2vjiU--Y1s1GFqVu6A8/

It would be nice to show a simple example inline here.

**Comment by OR13** [comment]
Partially done in https://ietf-wg-spice.github.io/draft-ietf-spice-sd-cwt/draft-ietf-spice-sd-cwt.html#section-3.2

**Comment by rohanmahy** [comment]
Partially done, but example could be more explicit.
